### PR TITLE
Move base/common/src to base/common/src/main/java

### PR DESCRIPTION
**Pull request by edewata**

### CODE REVIEW

**Review by cipherboy — APPROVED** [review]
One conflict. But good for mavenization? I'll take it! Please re-run CI after fixing conflict. :)

**Comment by edewata** [comment]
This if for Mavenization, but there's more directories to fix. I'll merge after CI. Thanks!

**Review by SilleBille — APPROVED** [review]
CI succeeds. Scripts look good. Thanks @edewata !

**Comment by edewata** [comment]
Thanks @SilleBille !

**Pull request merged**
