### PR TITLE
Make getStatus return JSON instead of XML

### PR DESCRIPTION
**Pull request by ckelleyRH**
Introduces `JSONObject` class to begin to replace instances of the
`XMLObject` class.

### CODE REVIEW

**Comment by ckelleyRH** [comment]
I have a simple script called `pki-status-all.sh` which does:
```
declare -a arr=("ca" "kra" "ocsp" "tks" "tps")

for i in "${arr[@]}"
do
   curl -s http://localhost.localdomain:8080/$i/admin/$i/getStatus
done
```
and produces the following result with this change, after deploying all subsystems:
```pki-all-status.sh 
{
  "Response" : {
    "State" : "1",
    "Type" : "CA",
    "Status" : "running",
    "Version" : "11.0.0-0.1.alpha1.fc34",
    "ProductVersion" : "Dogtag Certificate System"
  }
}{
  "Response" : {
    "State" : "1",
    "Type" : "KRA",
    "Status" : "running",
    "Version" : "11.0.0-0.1.alpha1.fc34",
    "ProductVersion" : "Dogtag Certificate System"
  }
}{
  "Response" : {
    "State" : "1",
    "Type" : "OCSP",
    "Status" : "running",
    "Version" : "11.0.0-0.1.alpha1.fc34",
    "ProductVersion" : "Dogtag Certificate System"
  }
}{
  "Response" : {
    "State" : "1",
    "Type" : "TKS",
    "Status" : "running",
    "Version" : "11.0.0-0.1.alpha1.fc34",
    "ProductVersion" : "Dogtag Certificate System"
  }
}{
  "Response" : {
    "State" : "1",
    "Type" : "TPS",
    "Status" : "running",
    "Version" : "11.0.0-0.1.alpha1.fc34",
    "ProductVersion" : "Dogtag Certificate System"
  }
}
```

**Comment by ckelleyRH** [comment]
@edewata all of "our" CI passes with this change, the failures are now in the `freeipa` tests. Are you familiar with that code at all?

**Comment by edewata** [comment]
I only worked on a small portion of IPA code, so it depends.

For this particular error, I see this in `/var/log/pki/pki-tomcat/systemd.log` in `ipa-33.zip`:
```
Jul 27 13:59:17 ipa.example.com ipa-pki-wait-running[2764]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='ipa.example.com', port=8080): Read timed out. (read timeout=1.0)
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]: Traceback (most recent call last):
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:   File "/usr/libexec/ipa/ipa-pki-wait-running", line 132, in <module>
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:     main()
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:   File "/usr/libexec/ipa/ipa-pki-wait-running", line 99, in main
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:     status, error = get_status(conn, CONNECTION_TIMEOUT)
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:   File "/usr/libexec/ipa/ipa-pki-wait-running", line 77, in get_status
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:     root = ElementTree.fromstring(response)
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:   File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 1347, in XML
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]:     parser.feed(text)
Jul 27 13:59:18 ipa.example.com ipa-pki-wait-running[2764]: xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```
The stack trace points to this code in IPA:
https://github.com/freeipa/freeipa/blob/master/install/tools/ipa-pki-wait-running.in#L77
So the IPA code is currently expecting an XML response.

I think there are several ways to address this:
1. Update `SystemStatusClient.get_status()` to return an XML response for backward compatibility.
2. Modify IPA to detect `get_status()` response type and handle both XML and JSON.
3. Assuming option 2 is already implemented, drop `get_status()` XML handler in IPA for PKI 11.0 or later.

We can either ask IPA team to implement option 2 and 3, or we create our own patch and submit a PR against IPa. If we want to create a patch, we can test that in our CI by building a patched IPA in our COPR repo.

**Comment by ckelleyRH** [comment]
@edewata the patch to `freeipa` has been merged, this change is pointing back at the nightly copr build and is passing all the CI (finally).

**Review by edewata — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
Thanks!

**Pull request merged**
