### PR TITLE
Move AddProfileCaAuditSigningCert.py

### PR DESCRIPTION
**Pull request by edewata**
The upgrade script for adding a new audit signing cert and deprecating the old audit signing cert has been moved from 10.10.0 to 10.10.2 to ensure that the changes will be applied properly.

https://bugzilla.redhat.com/show_bug.cgi?id=1875563

This is a follow-up for PR #3404.

### CODE REVIEW

**Review by cipherboy — CHANGES_REQUESTED** [review]
Shouldn't it go to `10.10.2` or `10.10.1` not `10.10.12`?

**Comment by edewata** [comment]
Good catch! Fixed.

**Review by cipherboy — APPROVED** [review]

**Comment by edewata** [comment]
Thanks! There's actually a pylint issue in the upgrade script. Let me fix that separately. Merging.

**Review by ladycfu — COMMENTED** [review]
looks good.

**Pull request merged**
