### PR TITLE
Update KRA servlets to use @WebServlet

### PR DESCRIPTION
**Pull request by edewata**

### CODE REVIEW

**Review by ckelleyRH — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
I re-ran the CI because there were several failures but I don't expect it will help, as there were a few recurring issues across  tests like cloning.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
> I re-ran the CI because there were several failures but I don't expect it will help, as there were a few recurring issues across tests like cloning.

Well look at that, it passed this time! No idea what was wrong the first time then.

**Comment by edewata** [comment]
@ckelleyRH @fmarco76 Thanks! Yeah, sometimes a bunch of the tests failed for no reason and worked again after restart.

**Pull request merged**
