### PR TITLE
Run shellcheck as GitHub action in PKI CI

### PR DESCRIPTION
**Pull request by ckelleyRH**
* Rename `sonarcloud.yml` to `code-analysis.yml`, add any additonal future
linters/scanners into this workflow.
* Currently there are ~100 errors, so the job fails. We can now start to address issues.
* Documentation for this Action can be found [here](https://github.com/marketplace/actions/shellcheck)

### CODE REVIEW

**Comment by ckelleyRH** [comment]
I turns out that the job will fail even for `WARNING`. If we desired, we could force it to fail only on `ERROR` with this additional line:
```
      with:
        severity: error
```

**Comment by fmarco76** [comment]
I do not get the list of errors. Did you check on your PC or I miss something.

Additionally, the [documentation](https://github.com/marketplace/actions/shellcheck#change-output-format) describes how to change the output format for the errors but how can we access it?

**Comment by fmarco76** [comment]
> do not get the list of errors

I get it. I think it is OK to have it fails on error for the moment and when we have no _Error_ move to _Warning_

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
> Additionally, the [documentation](https://github.com/marketplace/actions/shellcheck#change-output-format) describes how to change the output format for the errors but how can we access it?

I decided against modifying this and just had it print out as the default. I didn't expect to do anything fancy with the output, just fail if there were issues.

> I get it. I think it is OK to have it fails on error for the moment and when we have no Error move to Warning

Ack, I will add in the additional line and merge, thanks!

**Pull request merged**
