### PR TITLE
minor change for tps-activity job

### PR DESCRIPTION
**Pull request by ssidhaye**
Signed-off-by: Sumedh Sidhaye <ssidhaye@sumedhs.englab.pnq.redhat.com>

### CODE REVIEW

**Comment by amolkahat** [comment]
@ssidhaye Please resolve the conflicts and remove only, I'll merge this.

**Comment by edewata** [comment]
@06shalini Could you take a look at this? Thanks.

**Comment by 06shalini** [comment]
@edewata  We can close this MR.

**Comment by edewata** [comment]
Thanks!

**Pull request closed without merging**
