### PR TITLE
Remove unused logAudit.* and logError.* params

### PR DESCRIPTION
**Pull request by edewata**
The `CS.cfg` files have been modified to no longer provide `logAudit.*` and `logError.*` params.

The upgrade script has been updated to remove these params from existing instances.

### CODE REVIEW

**Comment by ckelleyRH** [comment]
What happened to the CI?

**Review by ckelleyRH — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@ckelleyRH Thanks!

Not sure what's going on with the CI, let me see if I can restart it.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 Thanks!

Apparently it was just a glitch in the CI system.

**Pull request merged**
