### PR TITLE
Added_doc_for_installing_CA_clone_with_secure_DS

### PR DESCRIPTION
**Pull request by PsOverflow**
Fixed the suggestions provided at https://github.com/dogtagpki/pki/pull/3485

Signed-off-by: Pritam Singh <prisingh@redhat.com>

### CODE REVIEW

**Comment by PsOverflow** [comment]
Preview:
https://github.com/dogtagpki/pki/blob/dd87210f0541cb09df09a501b1bb0a130721de76/docs/installation/ca/Installing_CA_Clone_with_Secure_Database_Connection.md

**Comment by edewata** [comment]
Just FYI, for the preview you might want to specify your branch instead of specific commit ID in the URL so it will get updated automatically if you make any changes:
> https:// github.com/**PsOverflow/pki**/blob/**Added_doc_for_installing_CA_clone_with_secure_DS**/docs/installation/ca/Installing_CA_Clone_with_Secure_Database_Connection.md

**Review by edewata — APPROVED** [review]
LGTM. Thanks!

**Comment by PsOverflow** [comment]
@edewata updated the preview doc link and merging PR. Thanks.

**Pull request merged**
