### PR TITLE
Add JSON mapper for UserCertData

### PR DESCRIPTION
**Pull request by edewata**
Issue #3567

### CODE REVIEW

**Comment by edewata** [comment]
@ckelleyRH There's a number of classes that need JSON mapping. Just let me know if you want to work on this so we can split the task. Might be a good exercise for Ciarán too.

**Comment by ckelleyRH** [comment]
Yeah I'm happy to pitch in with this, and I agree it would be useful for Ciarán too. I'll review in the morning, getting a bit late now!

How are you determining which classes are missing the mapping?

**Comment by edewata** [comment]
@ckelleyRH Just look for classes that have `@XmlRootElement`. I put the details in Issue #3567. Thanks!

**Review by ckelleyRH — APPROVED** [review]
LGTM.

**Comment by edewata** [comment]
@ckelleyRH Thanks!

**Pull request merged**
