### PR TITLE
Add test for LDAP-based CRL publishing

### PR DESCRIPTION
**Pull request by edewata**
Doc: https://github.com/dogtagpki/pki/wiki/Publishing-CRL-to-LDAP-Server

If audit is not required, this might resolve this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2089749

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 Thanks! I rebased and updated the doc.

**Review by ckelleyRH — APPROVED** [review]
LGTM

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 @ckelleyRH Thanks!

**Pull request merged**
