### PR TITLE
Add publish job

### PR DESCRIPTION
**Pull request by edewata**
A new job has been added to publish PKI images to GH Packages after the build job is complete.

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
The SCEP test looks to be failing because it is not available as a GitHub package yet?
The `update_version` script also failed, I have reproduced locally and will investigate.
Otherwise LGTM!

**Review by ckelleyRH — APPROVED** [review]

**Comment by ckelleyRH** [comment]
I have fixed the `update_version` script. It looks like someone updated the `phase` manually and it confused the script.

**Comment by edewata** [comment]
@fmarco76 @ckelleyRH Thanks!

The SCEP test has not been fixed yet. We do have SSCEP in GH Packages, but it was probably built for F36 so it wouldn't run in F34 container used by this branch. That'll be addressed separately later.

**Pull request merged**
