### PR TITLE
Update OCSP servlets to use @WebServlet (part 2)

### PR DESCRIPTION
**Pull request by edewata**

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Review by ckelleyRH — APPROVED** [review]
LGTM, and I think I might have figured out how to remove the  `<security-constraint>`s too...

**Comment by edewata** [comment]
@fmarco76 @ckelleyRH Thanks!

IIUC the `<security-constraint>` is still required:
https://docs.jboss.org/resteasy/docs/3.0.24.Final/userguide/html_single/#Securing_JAX-RS_and_RESTeasy
but if it can actually be removed feel free to create a PR for that. Thanks!

**Comment by ckelleyRH** [comment]
> @fmarco76 @ckelleyRH Thanks!
> 
> IIUC the `<security-constraint>` is still required: https://docs.jboss.org/resteasy/docs/3.0.24.Final/userguide/html_single/#Securing_JAX-RS_and_RESTeasy but if it can actually be removed feel free to create a PR for that. Thanks!

Allegedly there are annotation equivalents for `<security-constraint>`: https://www.codejava.net/java-ee/servlet/servletsecurity-httpmethodcontraint-and-httpconstraint-annotations-examples but I have not studied it in great detail. I'm not certain that it is exactly equivalent.

`<display-name>` can be put in the annotations though, as an attribute of `@WebServlet`: https://www.tutorialspoint.com/servlets/servlets-annotations.htm. This makes the ROOT web.xml obsolete because it is the only thing defined in there.

**Pull request merged**
