### PR TITLE
Add KRA and OCSP containers

### PR DESCRIPTION
**Pull request by edewata**
The `Dockerfile` has been updated to define new KRA and OCSP containers.

A new test has been added to create CA and KRA containers, then verify key archival and recovery. A new test has also been added to create CA and OCSP containers, then verify CRL publishing and revocation checking.

https://github.com/dogtagpki/pki/wiki/Deploying-KRA-on-Podman
https://github.com/dogtagpki/pki/wiki/Deploying-OCSP-on-Podman

### CODE REVIEW

**Review by fmarco76 — CHANGES_REQUESTED** [review]
I have a small concern with the restart operation which need to be verified/fixed before to merge.

**Comment by edewata** [comment]
@fmarco76 Thanks for the feedback! I have updated the tests to confirm that the containers can be restarted properly (except for `pki-server` container since it requires some additional changes). Yes, currently `pkispawn` indeed will run again on restart, but it should work just fine with existing config files (we already have tests for that scenario). Ideally it should run only once, but there are multiple scenarios that need to be considered (e.g. are there existing config files, are there existing certs, are there existing database, what if the certs are changed) so if that's OK I'd rather handle them in separately later to keep this PR simple.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 Thanks!

**Pull request merged**
