### PR TITLE
Provide a nickname with token and all tokens/passwords when modifying trust during installation

### PR DESCRIPTION
**Pull request by rcritten**
In an IPA replica installation with an HSM the audit trust is not being set.

It isn't set because the nickname is not available in the NSS database so certutil -M fails with "no such certifiate."

In order to add the trust one needs to authenticate to the token to find the cert. It also needs the NSS softokn password so the trust can be written.

certutil -f can take a file with token:password pairs and will search for the appropriate token.

The internal NSS token names are hardcoded because I could find no other way in an NSS tool to obtain the name other than scraping modutil -list output, which just seems awful. I can try to do that if desired.

### CODE REVIEW

**Comment by rcritten** [comment]
I've duplicated at least the KRA test failure locally, investigating.

**Review by edewata — APPROVED** [review]
LGTM. Do you know since when `certutil` supports this type of password file? We might need to update the NSS dependency in the spec file as well.

**Comment by edewata** [comment]
I'll merge the PR now, we can update the NSS dependency later if needed. Thanks!

**Comment by rcritten** [comment]
The code in NSS to find the token in a password file has been there since like 2008. I had no idea!
The problem is that certutil won't utilize it because it just keeps trying to authenticate to the token passed in, failing over and over. This is addressed by upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1782980 . Bob Relyea thinks this will get merged in Jan 2023.

**Pull request merged**
