### PR TITLE
Added man page for PKCS10Client

### PR DESCRIPTION
**Pull request by amolkahat**
Man page entry for PKCS10Client cli.

### CODE REVIEW

**Comment by amolkahat** [comment]
@edewata @tiran Please take a look.

**Comment by edewata** [comment]
You probably need to include the new man page in the pki-core.spec as well so it gets included in the build.

**Comment by amolkahat** [comment]
@edewata can you please take a look?

**Comment by edewata** [comment]
Thanks, Amol!

BTW, this patch was pushed into master branch (i.e. 10.6). If you need it for 10.5 branch you probably need to submit another pull request.

**Pull request merged**
