### PR TITLE
Strip debug symbols from executables

### PR DESCRIPTION
**Pull request by ckelleyRH**
Slightly reduces the size of compiled binaries.

### CODE REVIEW

**Comment by edewata** [comment]
Looks like there are failures in TPS and tools tests. I'm not familiar with the `-s` option. Is there a documentation?

**Comment by ckelleyRH** [comment]
> Looks like there are failures in TPS and tools tests. I'm not familiar with the `-s` option. Is there a documentation?

The build failures are unrelated (TPS is transient artefact upload issue; rpminspect failed because they updated the rules again). I will look at the docs again later, I didn't inspect the man page for the compiler or anything I looked for examples of this symbol stripping and they all did this (or something very similar).

**Comment by ckelleyRH** [comment]
@edewata - there's a link [here](http://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#Link-Options) to the option for GCC, but there is not much to say.

**Review by edewata — APPROVED** [review]
OK, I suppose this flag is only affecting the native tools. The server is purely Java (except for JSS). Feel free to merge. Thanks!

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
Thanks @edewata @fmarco76 !

**Pull request merged**
