### PR TITLE
Remove XML mapping from CMSRequestInfo

### PR DESCRIPTION
**Pull request by ckelleyRH**

### CODE REVIEW

**Comment by ckelleyRH** [comment]
Rebased on top of the two remaining #3693 PRs (#3715 & #3716 ) - hoping that now some of the JAXB mapping has been removed this will unlock some of the blocked tag-removal PRs like this one.

**Review by c-dorney — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@ckelleyRH Could you rebase this PR? Thanks.

**Comment by ckelleyRH** [comment]
@edewata rebased; not much left of it now :+1:

**Review by edewata — APPROVED** [review]
LGTM

**Pull request merged**
