### PR TITLE
Bug 1744095 - CMCResponse is not working as expected

### PR DESCRIPTION
**Pull request by ladycfu**
This patch fixes the issue that HttpClient extracting less bytes than
the actual data size from the HTTP response.
My investigation shows that there used to be 6 lines of headers, and
now it's down to 5.
The fix is to default to 5, but add an unadvertised numHeaderLines
that allows one to customize in case the server changes again.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744095

### CODE REVIEW

**Comment by cipherboy** [comment]
Uh, @edewata / @ladycfu, are there no HTTP libraries we can use here instead? That seems like the more sane solution... :)

**Comment by ladycfu** [comment]
> Uh, @edewata / @ladycfu, are there no HTTP libraries we can use here instead? That seems like the more sane solution... :)

I'm sure there is.  I'm just doing the minimum to fix the issue now.  Feel free to open another ticket against HttpClient and make improvements on it when you have time  ;-).

**Comment by edewata** [comment]
FYI, https://pagure.io/dogtagpki/issue/342

**Comment by cipherboy** [comment]
ACK @ladycfu sounds fine for now. :) And I guess @edewata was 6 years ahead of me. ;-)

**Pull request merged**
