### PR TITLE
Use try-with-resources in client and logging classes

### PR DESCRIPTION
**Pull request by ckelleyRH**

### CODE REVIEW

**Comment by edewata** [comment]
There are some weird failures. Are these caused by recent branching?

**Comment by fmarco76** [comment]
> There are some weird failures. Are these caused by recent branching?

Some errors are for the release of F38 but it seems there is also a problem with the changes (e.g. https://github.com/dogtagpki/pki/actions/runs/4756075420/jobs/8451392659?pr=4417#step:12:199)

**Comment by ckelleyRH** [comment]
> > There are some weird failures. Are these caused by recent branching?
> 
> Some errors are for the release of F38 but it seems there is also a problem with the changes (e.g. https://github.com/dogtagpki/pki/actions/runs/4756075420/jobs/8451392659?pr=4417#step:12:199)

Indeed, the `pylint` and `rpminspect` issues are known and I have raised internal tickets to fix them. The other 4 I think are because I mistakenly removed the entire `finally` clause from one `try-with-resources` statement. I had to back two streams out because there was some logic in there that would have required some refactoring, but I didn't reinstate the `close()` calls.

**Comment by ckelleyRH** [comment]
Hmm, apparently not - more thought required.

**Comment by ckelleyRH** [comment]
For now, I have backed out the changes to `../cmstools/HttpClient`, so we can incrementally move forward while I debug the failures.

**Review by edewata — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
Thanks @edewata @fmarco76 !

**Pull request merged**
