### PR TITLE
Automation: BZ: 1541853 Backslash in profile causes failure 

### PR DESCRIPTION
**Pull request by amolkahat**
Automation of BZ: 1541853 Backslash in profile causes failure

### CODE REVIEW

**Comment by frasertweedale** [comment]
I should review this one.  Will try to get to it this week.

**Comment by cipherboy** [comment]
@amolkahat Is this still needed? Could we get this rebased? When done, please ping Fraser for final review and merge. :-) Thanks!

**Comment by amolkahat** [comment]
Hey @cipherboy , this is still needed. You can merge this PR when CI get passed.

**Comment by SilleBille** [comment]
Just poking my nose through. The CI does not seem to pass. Maybe it's unrelated to this PR, but CA failed to start. Can this PR be rebased to match with current master? Also note that we have moved from Travis to GH Actions through PR #408

**Comment by edewata** [comment]
@06shalini Could you take a look at this as well? Feel free to close it if it's already covered in the current tests. Thanks!

**Pull request closed without merging**
