### PR TITLE
Remove Legacy VBScript Web Code

### PR DESCRIPTION
**Pull request by cipherboy**
No modern browser supports VBScript except IE 11. Microsoft announced its
removal and deprecation in August 2019. Every modern, graphical browser
supports JavaScript, including IE 2+, Edge, Safari, Chrome, and Firefox.

`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`

### CODE REVIEW

**Comment by edewata** [comment]
I think we can safely remove them, but I'd defer to @ladycfu or @jmagne.

**Comment by ladycfu** [comment]
@cipherboy I'm not familiar with scripts.  So I imagine if you use the latest IE now it will just work?  With your patch, did you try, say, doing an enrollment using IE and see if that really works?

**Comment by cipherboy** [comment]
@ladycfu No, I haven't -- I don't have access to IE. Do you?

**Comment by ladycfu** [comment]
> @ladycfu No, I haven't -- I don't have access to IE. Do you?

I think @jmagne does.  Try checking with him.

**Comment by cipherboy** [comment]
(And to answer your question, theoretically it should now behave however Firefox/Chrome behaves and we won't be special casing it. There's also some old ASP.NET code as well that we should remove).

**Comment by frasertweedale** [comment]
(I restarted one of the CI jobs to see if recent failures also occur for slightly older PRs whose CI is green; i.e. is it a travis CI infra issue as I suspect, or did something actually regress?)

**Comment by cipherboy** [comment]
@frasertweedale Different set of failed CI tests, so I'm inclined to blame Travis. Perhaps PKI should move to GH Actions :-)

**Comment by cipherboy** [comment]
@jmagne @ladycfu This has been rebased :)

**Review by edewata — APPROVED** [review]
@cipherboy @ladycfu I think if there's a problem with Microsoft browsers it needs to be fixed in JavaScript anyway, so it should be OK to remove the obsolete VBScripts. Sorry for the delay, it's only 15 months :)

**Comment by edewata** [comment]
@ladycfu confirmed on IRC. I'll merge. Thanks all!

**Pull request merged**
