### PR TITLE
Added pki-server run --with-valgrind

### PR DESCRIPTION
**Pull request by edewata**
The `--with-valgrind` option has been added to `pki-server run`
command to run the server with valgrind.

### CODE REVIEW

**Comment by edewata** [comment]
@cipherboy @SilleBille For some reason the JVM keeps crashing given a simple `pki ca-cert-find` command. Any idea?

```
$ pki-server run --with-valgrind --debug
INFO: Loading instance: pki-tomcat
INFO: Loading global Tomcat config: /etc/tomcat/tomcat.conf
INFO: Loading PKI Tomcat config: /usr/share/pki/etc/tomcat.conf
INFO: Loading instance Tomcat config: /etc/pki/pki-tomcat/tomcat.conf
INFO: Loading password config: /etc/pki/pki-tomcat/password.conf
INFO: Loading instance registry: /etc/sysconfig/pki/tomcat/pki-tomcat/pki-tomcat
INFO: Loading subsystem config: /var/lib/pki/pki-tomcat/ca/conf/CS.cfg
INFO: Loading subsystem registry: /var/lib/pki/pki-tomcat/ca/conf/registry.cfg
DEBUG: Command: sudo -u pkiuser /usr/sbin/pki-server upgrade --validate pki-tomcat --debug
DEBUG: Command: sudo -u pkiuser /usr/bin/pkidaemon start pki-tomcat
DEBUG: Environment variables:
DEBUG: - TOMCAT_CFG_LOADED: 1
DEBUG: - TOMCATS_BASE: /var/lib/tomcats/
DEBUG: - JAVA_HOME: /usr/lib/jvm/jre-1.8.0-openjdk
DEBUG: - CATALINA_HOME: /usr/share/tomcat
DEBUG: - CATALINA_TMPDIR: /var/lib/pki/pki-tomcat/temp
DEBUG: - JAVA_OPTS: 
DEBUG: - SECURITY_MANAGER: true
DEBUG: - NSS_DEFAULT_DB_TYPE: sql
DEBUG: - CATALINA_BASE: /var/lib/pki/pki-tomcat
DEBUG: - TOMCAT_USER: pkiuser
DEBUG: - CATALINA_PID: /var/run/pki/tomcat/pki-tomcat.pid
DEBUG: - TOMCAT_LOG: /var/log/pki/pki-tomcat/tomcat-initd.log
DEBUG: - PKI_VERSION: 10.9.0
DEBUG: - TOMCAT_SECURITY: true
DEBUG: - USE_NUXWDOG: false
DEBUG: - NAME: pki-tomcat
DEBUG: Command: sudo -u pkiuser valgrind --trace-children=yes --tool=massif /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -agentpath:/usr/lib/abrt-java-connector/libabrt-java-connector.so=abrt=on, -classpath /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar:/usr/lib/java/commons-daemon.jar -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.security.manager -Djava.security.policy==/etc/pki/pki-tomcat/catalina.policy org.apache.catalina.startup.Bootstrap start
==11550== Massif, a heap profiler
==11550== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==11550== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==11550== Command: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -agentpath:/usr/lib/abrt-java-connector/libabrt-java-connector.so=abrt=on, -classpath /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar:/usr/lib/java/commons-daemon.jar -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.security.manager -Djava.security.policy==/etc/pki/pki-tomcat/catalina.policy org.apache.catalina.startup.Bootstrap start
==11550== 
[CodeBlob (0x0000000007b01dd0)]
Framesize: 84
SafepointBlob
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:847), pid=11550, tid=0x0000000006101700
#  fatal error: exception happened outside interpreter, nmethods and vtable stubs at pc 0x0000000007b01e87
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
# Core dump written. Default location: /tmp/core or core.11550
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid11550.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
==11550== 
==11550== Process terminating with default action of signal 6 (SIGABRT): dumping core
==11550==    at 0x48B2E35: raise (in /usr/lib64/libc-2.29.so)
==11550==    by 0x489D894: abort (in /usr/lib64/libc-2.29.so)
==11550==    by 0x5093FAE: os::abort(bool) [clone .cold] (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x59D31B2: VMError::report_and_die() (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x537F345: report_fatal(char const*, int, char const*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5848C9D: SharedRuntime::continuation_for_implicit_exception(JavaThread*, unsigned char*, SharedRuntime::ImplicitExceptionKind) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x57B295A: JVM_handle_linux_signal (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x57A544B: signalHandler(int, siginfo_t*, void*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x48B2EBF: ??? (in /usr/lib64/libc-2.29.so)
==11550==    by 0x7B01E86: ???
==11550==    by 0x1A: ???
==11550==    by 0x7AC2D7F: ???
==11550==    by 0x7AC2D7F: ???
==11550==    by 0x7ABB4E6: ???
==11550==    by 0x5527674: JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5524DEE: JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5525472: JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Handle, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5943F23: SystemDictionary::load_instance_class(Symbol*, Handle, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5944889: SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5946805: SystemDictionary::resolve_or_fail(Symbol*, Handle, Handle, bool, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5376547: ConstantPool::klass_at_impl(constantPoolHandle, int, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5518439: InterpreterRuntime::_new(JavaThread*, ConstantPool*, int) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x7AE20C6: ???
==11550==    by 0x7ABB4E6: ???
==11550==    by 0x5527674: JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x54D2DB9: InstanceKlass::call_class_initializer_impl(instanceKlassHandle, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x54D32E6: InstanceKlass::initialize_impl(instanceKlassHandle, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x54D35F9: InstanceKlass::initialize(Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x58286C4: Reflection::invoke_constructor(oopDesc*, objArrayHandle, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x5589919: JVM_NewInstanceFromConstructor (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x7AD42CB: ???
==11550==    by 0x7AC2D7F: ???
==11550==    by 0x7AC2D7F: ???
==11550==    by 0x7AC2E53: ???
==11550==    by 0x7AC2D7F: ???
==11550==    by 0x7AC2FFC: ???
==11550==    by 0x7AC2FFC: ???
==11550==    by 0x7AC2FFC: ???
==11550==    by 0x7AC2FFC: ???
==11550==    by 0x7ABB4E6: ???
==11550==    by 0x5527674: JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x554A645: jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .isra.0] [clone .constprop.0] (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x554DF35: jni_CallStaticVoidMethod (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
==11550==    by 0x4842886: JavaMain (in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc30.x86_64/jre/lib/amd64/jli/libjli.so)
==11550==    by 0x4A6B4BF: start_thread (in /usr/lib64/libpthread-2.29.so)
==11550==    by 0x4977162: clone (in /usr/lib64/libc-2.29.so)
==11550== 
```

**Comment by SilleBille** [comment]
@edewata This seems to be an issue with JIT. You can disable JIT by passing this option to java: `-Djava.compiler=NONE`

A quick test actually was able to list the certs. However, **note that it took me ~4 mins to get the output from `pki ca-cert-find`**
````
# pki-server run --with-valgrind
==54426== Massif, a heap profiler
==54426== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==54426== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==54426== Command: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -agentpath:/usr/lib/abrt-java-connector/libabrt-java-connector.so=abrt=on, -classpath /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar:/usr/lib/java/commons-daemon.jar -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.compiler=NONE -Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
==54426== 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/slf4j/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/pki/server/webapps/pki/WEB-INF/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/slf4j/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
````

**Comment by SilleBille** [comment]
From the error you posted, it seems like `hsdis-amd64.so` is missing. 

https://askubuntu.com/questions/710392/java-8-oracle-1-8-0-66-problem-with-printassembly-could-not-load-hsdis-amd64

Hoever, I was not able to find a solution on Fedora. But, I found this Docker image that generates the file for you: https://github.com/YaSuenag/hsdis-builder

**Comment by edewata** [comment]
@SilleBille Thanks! I've added `-Djava.compiler=NONE` in the latest code. I've also installed the debuginfo (forgot to do that earlier). I have not built hsdis-amd64.so yet. Now I'm trying it again, but after 15 mins I still haven't seen any results. It looks like `massif-amd64-linux` is consuming 100% CPU. I'll try hsdis-amd64.so later.

**Comment by edewata** [comment]
Thanks! Merging per discussion with @SilleBille and @cipherboy.

**Pull request merged**
