### PR TITLE
Disable LTO test in RPMInspect

### PR DESCRIPTION
**Pull request by ckelleyRH**

### CODE REVIEW

**Review by edewata — APPROVED** [review]
Some tests might need to be restarted, but the change LGTM. Feel free to merge if it fixes the problem.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
@edewata @fmarco76 - I additionally attempted to disable the LTO test in RPMInspect as even though I explicitly disabled it in another PR the test is still confused about that flag. I don't think it is important, so I disabled it, but if you think different do say.

**Comment by ckelleyRH** [comment]
OK, so it turns out that there is a bug in RPMInspect that prevents it from finding the allowed licence DB for Fedora. I have switched back to the v1.11 dev package to pick up the fix, we can switch back to stable later when v1.11 is released. Hopefully with the LTO test disabled and the dev packaged restored the CI should work again.

**Comment by ckelleyRH** [comment]
Now that I have learned that "License" is both a verb and a noun in US English, there is a chance we might have success ^_^

**Comment by ckelleyRH** [comment]
So it turns out my confusion is borne from there being a "top level" LTO test (which passes) and a subtask of `annocheck`, also called `lto`, which was failing. In order to skip that test I had to create a profile for `rpminspect`. In the process I was able to tidy up a bit more stuff elsewhere too.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Review by edewata — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
Thanks @edewata @fmarco76 !

**Pull request merged**
