### PR TITLE
Add tests for next begin/end numbers

### PR DESCRIPTION
**Pull request by edewata**
The tests for CA with sequential serial numbers have been updated to verify the `dbs.nextBegin...` and `dbs.nextEnd...` parameters.

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 Thanks!

I'm actually curious why we don't see the next begin/end params for certs. We'll investigate that separately.

**Comment by fmarco76** [comment]
> I'm actually curious why we don't see the next begin/end params for certs. We'll investigate that separately.

Not clear, we have the next parameters. Could you explain what was expected?

**Comment by edewata** [comment]
Ah yes, sorry. There's actually a `dbs.nextBeginSerialNumber` in `ca-sequential-test.yml` (I missed that) but not in `ca-clone-sequential-test.yml`. I guess it's just a matter of picking a good config params for testing.

**Pull request merged**
