### PR TITLE
Update CRMFPopClient to display hex request ID

### PR DESCRIPTION
**Pull request by edewata**

### CODE REVIEW

**Review by ckelleyRH — COMMENTED** [review]
Does this fix a bug or a cosmetic improvement? There's no description in either the commit or the PR.

**Comment by edewata** [comment]
Just cosmetic. Basically we want to display request IDs as hex numbers everywhere.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
> Just cosmetic. Basically we want to display request IDs as hex numbers everywhere.

OK, thanks!

**Review by ckelleyRH — APPROVED** [review]

**Comment by edewata** [comment]
@ckelleyRH @fmarco76 Thanks!

**Pull request merged**
