### PR TITLE
AccountService v2

### PR DESCRIPTION
**Pull request by fmarco76**
To implement the `AccountService` in all the sub-systems a new servlet and related filter is created in each subsystem. To avoid code duplication the actual operation is delegated to a common object of `AccountServletBase`.

### CODE REVIEW

**Comment by fmarco76** [comment]
@edewata Reviewing the code I noticed that TPS account is slightly different so I need to modify the code to be the same.

**Comment by fmarco76** [comment]
Now it is implementing the v1 behaviour for all subsystems

**Review by edewata — APPROVED** [review]
LGTM. It looks consistent with the original code.

**Comment by fmarco76** [comment]
@edewata Thanks!

**Pull request merged**
