### PR TITLE
Add test for CA installation with non-default user

### PR DESCRIPTION
**Pull request by edewata**
A new job has been added to test CA installation with non-default user and group. The server process should be running as the non-default user.

### CODE REVIEW

**Comment by edewata** [comment]
There's an `rpminspect` failure, but it doesn't seem to be caused by this PR.

**Review by fmarco76 — APPROVED** [review]
LGTM

**Review by ckelleyRH — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 @ckelleyRH Thanks!

**Pull request merged**
