### PR TITLE
Bug-2008319-pkispawn EC subCA 2-step failure in FIPS mode

### PR DESCRIPTION
**Pull request by ladycfu**
This patch addressed issue reported on failure with EC subCA 2-step
installation in FIPS mode.
My investigation reveals that certutil -R would fail in create_request nssdb.py.
I found two different commits having attempts to fix the same issue:
  - f1f32c31d51dffb93e7874d8c4dd0325136c4db7
  - 8bf682a9e39a7963d5e3bf50b81580839c2e11c4
However, the the resulting code appears to NOT contain the working copy.

I pulled out code in this area in 10.2 as a reference to address the issue.
It appears to fix the problem.  I was able to create subCA successfully
in the FIPS environment on both soft token and hsm.

fixes https://bugzilla.redhat.com/show_bug.cgi?id=2008319

### CODE REVIEW

**Comment by frasertweedale** [comment]
@ladycfu nack.

Testing the following config (which is the feature my original commits implemented), fails with error:

```
[ftweedal@rhel79-0 ~]$ cat ca.cfg
[DEFAULT]
pki_server_database_password=4me2Test

[CA]
pki_req_ski=DEFAULT

pki_admin_email=caadmin@example.com
pki_admin_name=caadmin
pki_admin_nickname=caadmin
pki_admin_password=4me2Test
pki_admin_uid=caadmin

pki_client_database_password=4me2Test
pki_client_database_purge=False
pki_client_pkcs12_password=4me2Test

pki_ds_base_dn=dc=ca,dc=pki,dc=example,dc=com
pki_ds_database=ca
pki_ds_password=4me2Test

pki_security_domain_name=EXAMPLE

pki_ca_signing_nickname=ca_signing
pki_ocsp_signing_nickname=ca_ocsp_signing
pki_audit_signing_nickname=ca_audit_signing
pki_sslserver_nickname=sslserver
pki_subsystem_nickname=subsystem

pki_external=True
pki_external_step_two=False

pki_ca_signing_csr_path=ca_signing.csr

[ftweedal@rhel79-0 ~]$ sudo pkispawn -f ca.cfg -s CA
[sudo] password for ftweedal: 
Log file: /var/log/pki/pki-ca-spawn.20211102003110.log
Loading deployment configuration from ca.cfg.
Installing CA into /var/lib/pki/pki-tomcat.
Storing deployment configuration into /etc/sysconfig/pki/tomcat/pki-tomcat/ca/deployment.cfg.

Installation failed: 'NSSDatabase' object has no attribute 'get_password_file'
```

Note: it is the `pki_req_ski=DEFAULT` feature that my commits added, and which this commit breaks.

I don't think you can update the code match to match the code in the v10.6+ branch.  The 10.5 code is
different because a lot of the `pkispawn` implementation was rewritten between 10.5 and 10.6.  A more
targeted approach to resolving the ECC issue on the 10.5 branch is required.

**Comment by ladycfu** [comment]
@frasertweedale I pulled out the latest code from DOGTAG_10_5_BRANCH and tried adding the pki_req_ski=DEFAULT as you suggested in a 2-step installation.  I used RSA just to see if the basics work.  It failed with the following.  Please let me know what I missed.  BTW, I captured the following using script as the log doesn't always captures everything on screen. 
...
pkispawn    : INFO     ....... generating ca_signing CSR in /etc/pki/ca_reqSki.csr
pki.server  : INFO     Getting signing cert info for ca
pki.nssdb   : DEBUG    Command: openssl rand -out /tmp/tmpgb6lJ9 2048


Generating key.  This may take a few moments...

pki.nssdb   : DEBUG    Command: certutil -R -d /var/lib/pki/rhcs94-CA-cfu-hsm1_rsa110321/alias -f /tmp/tmphVhWU3/password.txt -s cn=CA Signing Certificate,ou=rhcs94-CA-cfu-hsm1_rsa110321,o=rhcs94-CA_cfu-rsa-110321 -o /tmp/tmpzdCZy5/request.bin -k 638485a007113638299dd9b8ff92d1d78c55c658
pkispawn    : DEBUG    ....... Error Type: Exception
pkispawn    : DEBUG    ....... Error Message: Failed to generate certificate request. RC: 255

**Comment by ladycfu** [comment]
@frasertweedale I couldn't attach my pkispawn file for some reason.  This was done on a 7.x in FIPS mode btw.  Here I pasted the content below:
[DEFAULT]
pki_instance_name=rhcs94-CA-cfu-hsm1_rsa110321
pki_https_port=18444
pki_http_port=18081

#Admin
pki_admin_key_type=rsa
pki_admin_password=SECret.123

#client Dir
pki_client_pkcs12_password=SECret.123

pki_ds_bind_dn=cn=Directory Manager
pki_ds_ldap_port=389
pki_ds_password=netscape
pki_ds_remove_data=True

#Token
#pki_hsm_enable=True
#pki_hsm_libfile=/opt/nfast/toolkits/pkcs11/libcknfast.so
#pki_hsm_modulename=nfast

#Security Domain
pki_security_domain_hostname=cfuhsm1.sjc.redhat.com
pki_security_domain_name=rhcs94-CA_cfu-rsa-110321
pki_security_domain_password=SECret.123

[Tomcat]
pki_ajp_port=18019
pki_tomcat_server_port=18015

[CA]
pki_req_ski=DEFAULT
pki_external=True
pki_external_step_two=False

pki_import_admin_cert=False

# Enable random serial numbers
#pki_random_serial_numbers_enable=True

pki_admin_email=example@testdomain.com
pki_admin_name=caadmin
pki_admin_nickname=PKI CA Administrator for cfuHSM1 RSA
pki_admin_uid=caadmin

pki_ds_database=slapd-cfuhsm-rsa110321
pki_ds_hostname=cfuhsm1.sjc.redhat.com

pki_ca_signing_csr_path=/etc/pki/ca_reqSki.csr

**Comment by ladycfu** [comment]
@frasertweedale @edewata , I created a fresh PR to replace this one: https://github.com/dogtagpki/pki/pull/3817
Thanks Fraser for the review and comment.  Even though the 10.2.1 code was referenced in part, they are necessary pieces to fix the ECC subCA creation issue.  In the new PR, I was more careful to not touch code involving the SKI in request feature, and only limit my changes to the absolute necessary things.  Thanks.

**Pull request closed without merging**
