### PR TITLE
Remove unused subsystem webapp folders

### PR DESCRIPTION
**Pull request by edewata**
`pkispawn` has been modified to no longer create the subsystem `webapps` folders.

An upgrade script has been added to remove the folders from existing instances.

https://github.com/edewata/pki/blob/upgrade/docs/changes/v11.1.0/Server-Changes.adoc

### CODE REVIEW

**Review by ckelleyRH — APPROVED** [review]
LGTM!

**Review by ckelleyRH — COMMENTED** [review]
L31 is upsetting the linter though :smile:

**Review by c-dorney — APPROVED** [review]
LGTM

**Review by ckelleyRH — APPROVED** [review]

**Comment by edewata** [comment]
@ckelleyRH @c-dorney Thanks! It's fixed now.

**Pull request merged**
