### PR TITLE
Add JSON wrappers for classes org.dogtagpki.common

### PR DESCRIPTION
**Pull request by ckelleyRH**
Requires overriding `equals()` and `hashCode()` in `Link` class, otherwise the
equals check for `ConfigData` fails on object equivalence for the Links.

### CODE REVIEW

**Comment by ckelleyRH** [comment]
Interestingly the missing items appear to be in our code, not the dependencies, so not sure what is happening here yet.

**Comment by edewata** [comment]
Looks like the `CAInfoTest` is meant to test `CAInfo` which is a common/client class, but it makes references to `CAInfoService` which only exists on the server side. I think the solution is to move the constants from `CAInfoService` into `CAInfo` so they can be used by both classes.

**Comment by ckelleyRH** [comment]
Good spot, thanks!

**Review by edewata — APPROVED** [review]
LGTM

**Pull request merged**
