### PR TITLE
Remove bashisms

### PR DESCRIPTION
**Pull request by StephenCoady**
As per https://pagure.io/dogtagpki/issue/2249

Signed-off-by: Stephen Coady <scoady@redhat.com>

### CODE REVIEW

**Comment by StephenCoady** [comment]
misbehaving formatter is diluting the PR. Will push again shortly.

**Comment by StephenCoady** [comment]
@cipherboy did I miss somewhere?

**Comment by cipherboy** [comment]
@StephenCoady I wasn't speaking to that (hence, "I"m not sure if..."). I'm not familiar enough with all of Dogtag and its scripts to comment on that...

I'm merely commenting that the changes is in this changeset are good changes. :)

**Comment by cipherboy** [comment]
@geetikakay Do you mind reviewing these QE test script changes and merging if everything looks good? Thanks! :)

**Comment by geetikakay** [comment]
@cipherboy This is okay but there tests might not hold good in versions later >=DOGTAG_10_0_BRANCH
Because there are lot of changes done and we moved to pytest with those changes.
We have this point to make : should we remove bash tests from branches >=DOGTAG_10_0_BRANCH

**Comment by cipherboy** [comment]
Hi @geetikakay. I think that's fine. Please open a new PR removing the old bash tests from the correct branches! :-) 

(I think that's master, v10.8, v10.7, and DOGTAG_10_6_BRANCH -- those are all the RHEL 8 branches).

**Pull request merged**
