### PR TITLE
Add test for CA installation with CMC

### PR DESCRIPTION
**Pull request by edewata**
Docs:
* https://github.com/dogtagpki/pki/blob/master/docs/installation/ca/Installing_CA_with_External_CA_Signing_Certificate.md
* https://github.com/dogtagpki/pki/wiki/Issuing-CA-Signing-Certificate-with-CMC

### CODE REVIEW

**Review by ckelleyRH — APPROVED** [review]
LGTM, but I am not an expert in this area by any stretch!

**Comment by edewata** [comment]
@ckelleyRH Thanks!

I simplified the test to use the whole cert chain instead of just the leaf cert for installation step 2.

**Review by ladycfu — APPROVED** [review]
I'm not that familiar with the language used here, but as far as I could tell, the logic for installing a subCA using two-step with CMC looks good.

**Comment by edewata** [comment]
@ladycfu Thanks!

Just FYI, `docker exec <container> <command>` means that it's executing the command inside the specified container. We use containers in the CI as virtual machines.

**Pull request merged**
