### PR TITLE
Update pom.xml to latest Jackson/jaxb-api versions

### PR DESCRIPTION
**Pull request by ckelleyRH**

### CODE REVIEW

**Comment by edewata** [comment]
Hmm.. it looks like the actual Maven build in Azure failed.

**Comment by ckelleyRH** [comment]
> 

Yeah, not looked into why yet - I got bored of seeing the `rpminspect` job fail so I'm away fixing that first.

**Comment by ckelleyRH** [comment]
OK, so https://github.com/dogtagpki/pki/pull/4313 should fix the `rpminspect` issue here so we can ignore that failure and this failure was because I forgot to update the artefact name to reflect the change in ownership. Should pass now.

**Comment by ckelleyRH** [comment]
So much nicer when everything is green in the CI isn't it :smile:

**Review by fmarco76 — APPROVED** [review]
LGTM!

**Pull request merged**
